In [2]:
import numpy as np

In [6]:
a =  np.array([1, 2, 3, 4, 5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a * b 
d = a @ b
e = np.dot(a,b)
# dot product (sum of element-wise multiplies)
print(c)
print(d)
print(e)

[ 2  8 18 32 50 72 98]
280
280


In [5]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b =np.array([2,4,6,8])
print("\nPrinting array a..")
print(a)
print("\nPrinting array b..")
print(b)
print("\nPrinting a+b..")
print(a+b)



Printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing array b..
[2 4 6 8]

Printing a+b..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


Iteration

In [7]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
print("Printing array:\n ",a)
print("\nIterating over rows..")
for x in np.nditer(a):
    print(x,end=", ")

Printing array:
  [[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Iterating over rows..
1, 2, 3, 4, 2, 4, 5, 6, 10, 20, 39, 3, 

3-D Array